/// The enum itemizes customizable phrases.
enum FauiPhrases {
  SignInTitle,
  CreateAccountTitle,
  ForgotPasswordTitle,
  ForgotPassordTitle,
  VerifyEmailTitle,
  ResetPasswordTitle,
  EmailTextField,
  CreateAccountButton,
  HaveAccountLink,
  PasswordTextField,
  SignInButton,
  CreateAccountLink,
  SignInLink,
  SendPasswordResetLinkButton,
  WeSentVerificationEmailMessage,
  WeSentLinkToResetPasswordMEssage,
  ForgotPassordLink,
}
